# Pandas Testing

Pandas Notes

## Pandas Basics

Import the Pandas Library with an alias
#### RUN THIS EACH TIME YOU OPEN THE FILE

In [1]:
import pandas as pd

### Dataframes

We can make a dataframe using the DataFrame function.

In [18]:
DataFrame = pd.DataFrame({'Zenless Zone Zero': ['Vivian'], 'Genshin Impact' : ['Raiden Shogun']})
DataFrame

  Zenless Zone Zero Genshin Impact
0            Vivian  Raiden Shogun

Right now, the index is not very descriptive. We can change that by adding a comma and setting index = 'Female'.

In [20]:
DataFrame = pd.DataFrame({'Zenless Zone Zero': ['Vivian'], 'Genshin Impact' : ['Raiden Shogun']}, index = ['Female'])
DataFrame

       Zenless Zone Zero Genshin Impact
Female            Vivian  Raiden Shogun

Let us also add another row including male characters.

In [21]:
DataFrame = pd.DataFrame({'Zenless Zone Zero': ['Vivian','Lighter'], 'Genshin Impact' : ['Raiden Shogun','Kaedehara Kazuha']}, index = ['Female','Male'])
DataFrame

       Zenless Zone Zero    Genshin Impact
Female            Vivian     Raiden Shogun
Male             Lighter  Kaedehara Kazuha

### Series

If Dataframes are tables, then a series is a list of one thing. They are essentially one column of a dataframe. We can create them using the Series function.

In [23]:
Series = pd.Series(['Chocolate', 'Vanilla', 'Strawberry', 'Mint Chocolate Chip'])
Series

0              Chocolate
1                Vanilla
2             Strawberry
3    Mint Chocolate Chip
dtype: str

Like Dataframes, we can assign indexes. We can also name the series.

In [25]:
Series = pd.Series(['Chocolate', 'Vanilla', 'Strawberry', 'Mint Chocolate Chip'], index = ['Best', 'Good', 'Okay','Bad'], name = 'Ice Cream Preferences')
Series

Best              Chocolate
Good                Vanilla
Okay             Strawberry
Bad     Mint Chocolate Chip
Name: Ice Cream Preferences, dtype: str

## Reading CSVs

CSV's are a common way to store DataFrames. We can import the sales.csv file by using read_csv.

In [4]:
df = pd.read_csv('(testing) sales.csv')
df

    day  kind        key                      name  units  revenue  best_price
0    11  Item         26             Deck Box Blue      3    61.50       20.50
1    11  Item         88             System Gate 2      1    45.50       45.50
2    11  Item         86               Mafia Works      1    44.50       44.50
3    11  Item          0           Basic Card Pack     22    74.80        3.40
4    11  Item          2            Rare Card Pack      2    10.00        5.00
5    11  Item         30             D20 Dice Blue      5    85.00       17.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
8    11  Item         31            D20 Dice Black      1    11.76       11.76
9    11  Item          3             Rare Card Box      1    40.00       40.00
10   11  Card     0-10-4                   EX Rare      1    17.08       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item          1            Basic Card Box      2    58.00       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card   0-39-4-F            EX Common Foil      1   645.00      645.00

As you can see it imported a table of all our current sales data including the day of the transaction, the kind of item, the internal key the game stores the item as, the name of the item, the amount of units sold, item revenue, and the highest price it was sold for that day.

We can clean up the default index of 1 through 14 in the first column and change it to the first column in our table.

In [5]:
df_clean = pd.read_csv('(testing) sales.csv', index_col = [0])
df_clean

     kind        key                      name  units  revenue  best_price
day
11   Item         26             Deck Box Blue      3    61.50       20.50
11   Item         88             System Gate 2      1    45.50       45.50
11   Item         86               Mafia Works      1    44.50       44.50
11   Item          0           Basic Card Pack     22    74.80        3.40
11   Item          2            Rare Card Pack      2    10.00        5.00
11   Item         30             D20 Dice Blue      5    85.00       17.00
11   Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
11   Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
11   Item         31            D20 Dice Black      1    11.76       11.76
11   Item          3             Rare Card Box      1    40.00       40.00
11   Card     0-10-4                   EX Rare      1    17.08       17.08
11   Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
11   Item          1            Basic Card Box      2    58.00       29.00
11   Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
11   Card   0-39-4-F            EX Common Foil      1   645.00      645.00

In this case, it would probably be best to keep the default index. So we will being using 'df' as the main dataframe.

### Analyze the Table

We can use the .shape function to show how many rows and columns our table has. The output is in the format: (rows, columns).

In [5]:
df.shape

(15, 7)

We can return the first five rows of the csv using head. We can also input a number into the parenthesis to list that amount of rows.

In [5]:
df.head()

   day  kind key             name  units  revenue  best_price
0   11  Item  26    Deck Box Blue      3     61.5        20.5
1   11  Item  88    System Gate 2      1     45.5        45.5
2   11  Item  86      Mafia Works      1     44.5        44.5
3   11  Item   0  Basic Card Pack     22     74.8         3.4
4   11  Item   2   Rare Card Pack      2     10.0         5.0

In [6]:
df.head(3)

   day  kind key           name  units  revenue  best_price
0   11  Item  26  Deck Box Blue      3     61.5        20.5
1   11  Item  88  System Gate 2      1     45.5        45.5
2   11  Item  86    Mafia Works      1     44.5        44.5

We can also do the same with the tail function. It is almost identical to the head function except it returns the last five rows by default. Inputting a number into the parenthesis inputs the last n number of rows instead of the first n number of rows.

In [7]:
df.tail()

    day  kind       key                      name  units  revenue  best_price
10   11  Card    0-10-4                   EX Rare      1    17.08       17.08
11   11  Card  0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item         1            Basic Card Box      2    58.00       29.00
13   11  Card  0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card  0-39-4-F            EX Common Foil      1   645.00      645.00

In [8]:
df.tail(3)

    day  kind       key                      name  units  revenue  best_price
12   11  Item         1            Basic Card Box      2    58.00       29.00
13   11  Card  0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card  0-39-4-F            EX Common Foil      1   645.00      645.00

We can also index a specific column using standard python indexing.

In [6]:
df['name']

0                Deck Box Blue
1                System Gate 2
2                  Mafia Works
3              Basic Card Pack
4               Rare Card Pack
5                D20 Dice Blue
6     Silver Edition Rare Foil
7     Silver Edition Rare Foil
8               D20 Dice Black
9                Rare Card Box
10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
14              EX Common Foil
Name: name, dtype: str

We can also use this format:

In [7]:
df.name

0                Deck Box Blue
1                System Gate 2
2                  Mafia Works
3              Basic Card Pack
4               Rare Card Pack
5                D20 Dice Blue
6     Silver Edition Rare Foil
7     Silver Edition Rare Foil
8               D20 Dice Black
9                Rare Card Box
10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
14              EX Common Foil
Name: name, dtype: str

This only works because our column does not have any reserved characters or spaces. If our column was called "Item Name," df.Item Name would not work. df.Item_Name would work.

We can also index a specific value.

In [9]:
df.name[0]

'Deck Box Blue'

### Pandas Indexing

That was indexing using normal python syntax, but pandas also has its own functions for indexing.

In [10]:
df.iloc[0]

day                      11
kind                   Item
key                      26
name          Deck Box Blue
units                     3
revenue                61.5
best_price             20.5
Name: 0, dtype: object

This retrieves the information from the first row and puts it in a nice series for us.

We can also retrieve a specific value using iloc.

In [13]:
df.iloc[0,3]

'Deck Box Blue'

This retrieves the value from row 0 in column 3 of table df, not the series df.iloc[0]. Do not base your iloc function off this series df.iloc[0] output as then this function above will likely give you an undesired input. Let see what happens if you do look at the series and base it off that.

We want row 4 and column 2 of the series.

In [14]:
df.iloc[4,2]

'2'

As you can see it gives us some random value. This is because it is based off the df dataframe not this series.

We can retrieve an entire column using iloc.

In [17]:
df.iloc[:,3]

0                Deck Box Blue
1                System Gate 2
2                  Mafia Works
3              Basic Card Pack
4               Rare Card Pack
5                D20 Dice Blue
6     Silver Edition Rare Foil
7     Silver Edition Rare Foil
8               D20 Dice Black
9                Rare Card Box
10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
14              EX Common Foil
Name: name, dtype: str

The colon tells pandas to read every row and return column 3 only.

We can also use iloc to select a range of values.

In [18]:
df.iloc[:3, 3]

0    Deck Box Blue
1    System Gate 2
2      Mafia Works
Name: name, dtype: str

The colon infront of the row 3 statement tells pandas to return rows 1-3.

In [19]:
df.iloc[1:3,3]

1    System Gate 2
2      Mafia Works
Name: name, dtype: str

This tells pandas to return just the second and third rows.

We can also use negative numbers in indexing.

In [21]:
df.iloc[-1,3]

'EX Common Foil'

This returns the last value in the column.

In [24]:
df.iloc[-5:-1,3]

10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
Name: name, dtype: str

This returns the 2nd last value to the 5th last value.

#### loc function vs iloc

loc is used with row or column names while iloc using numerical indexing to determine what row/column to return.

In [26]:
df.loc[:,'name']

0                Deck Box Blue
1                System Gate 2
2                  Mafia Works
3              Basic Card Pack
4               Rare Card Pack
5                D20 Dice Blue
6     Silver Edition Rare Foil
7     Silver Edition Rare Foil
8               D20 Dice Black
9                Rare Card Box
10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
14              EX Common Foil
Name: name, dtype: str

This returns every row of the 'name' column.

In [28]:
df.iloc[:,3]

0                Deck Box Blue
1                System Gate 2
2                  Mafia Works
3              Basic Card Pack
4               Rare Card Pack
5                D20 Dice Blue
6     Silver Edition Rare Foil
7     Silver Edition Rare Foil
8               D20 Dice Black
9                Rare Card Box
10                     EX Rare
11    Silver Edition Rare Foil
12              Basic Card Box
13    Silver Edition Rare Foil
14              EX Common Foil
Name: name, dtype: str

This iloc returns the exact same output but associates the 'name' column with the third column.

In [29]:
df.loc[0,'name']

'Deck Box Blue'

This returns the first value of the column.

In [31]:
df.iloc[0,3]

'Deck Box Blue'

As does this.

Loc is more intuitive to use in certain cases as the column names are usually representative.

In [39]:
df.loc[:,['kind','name','units','revenue']]

    kind                      name  units  revenue
0   Item             Deck Box Blue      3    61.50
1   Item             System Gate 2      1    45.50
2   Item               Mafia Works      1    44.50
3   Item           Basic Card Pack     22    74.80
4   Item            Rare Card Pack      2    10.00
5   Item             D20 Dice Blue      5    85.00
6   Card  Silver Edition Rare Foil      1    31.00
7   Card  Silver Edition Rare Foil      1    33.00
8   Item            D20 Dice Black      1    11.76
9   Item             Rare Card Box      1    40.00
10  Card                   EX Rare      1    17.08
11  Card  Silver Edition Rare Foil      1    29.33
12  Item            Basic Card Box      2    58.00
13  Card  Silver Edition Rare Foil      1    25.32
14  Card            EX Common Foil      1   645.00

This is much easier to remember than the exact positions of the columns.

In [41]:
df.iloc[:,[1,3,4,5]]

    kind                      name  units  revenue
0   Item             Deck Box Blue      3    61.50
1   Item             System Gate 2      1    45.50
2   Item               Mafia Works      1    44.50
3   Item           Basic Card Pack     22    74.80
4   Item            Rare Card Pack      2    10.00
5   Item             D20 Dice Blue      5    85.00
6   Card  Silver Edition Rare Foil      1    31.00
7   Card  Silver Edition Rare Foil      1    33.00
8   Item            D20 Dice Black      1    11.76
9   Item             Rare Card Box      1    40.00
10  Card                   EX Rare      1    17.08
11  Card  Silver Edition Rare Foil      1    29.33
12  Item            Basic Card Box      2    58.00
13  Card  Silver Edition Rare Foil      1    25.32
14  Card            EX Common Foil      1   645.00

It is however up to preference and both achieve the same goal reasonably.

You can set the index to a specific column as well.

In [6]:
df.set_index("name")

                          day  kind        key  units  revenue  best_price
name
Deck Box Blue              11  Item         26      3    61.50       20.50
System Gate 2              11  Item         88      1    45.50       45.50
Mafia Works                11  Item         86      1    44.50       44.50
Basic Card Pack            11  Item          0     22    74.80        3.40
Rare Card Pack             11  Item          2      2    10.00        5.00
D20 Dice Blue              11  Item         30      5    85.00       17.00
Silver Edition Rare Foil   11  Card   0-14-2-F      1    31.00       31.00
Silver Edition Rare Foil   11  Card  0-109-2-F      1    33.00       33.00
D20 Dice Black             11  Item         31      1    11.76       11.76
Rare Card Box              11  Item          3      1    40.00       40.00
EX Rare                    11  Card     0-10-4      1    17.08       17.08
Silver Edition Rare Foil   11  Card   0-18-2-F      1    29.33       29.33
Basic Card Box             11  Item          1      2    58.00       29.00
Silver Edition Rare Foil   11  Card   0-57-2-F      1    25.32       25.32
EX Common Foil             11  Card   0-39-4-F      1   645.00      645.00

### Conditional Selection

In [7]:
df.revenue >= 50

0      True
1     False
2     False
3      True
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14     True
Name: revenue, dtype: bool

We can return a logical series by inputting a conditonal statement.

In [8]:
df.loc[df.revenue >= 50]

    day  kind       key             name  units  revenue  best_price
0    11  Item        26    Deck Box Blue      3     61.5        20.5
3    11  Item         0  Basic Card Pack     22     74.8         3.4
5    11  Item        30    D20 Dice Blue      5     85.0        17.0
12   11  Item         1   Basic Card Box      2     58.0        29.0
14   11  Card  0-39-4-F   EX Common Foil      1    645.0       645.0

We can also nest the conditonal statement in the loc statement to select the relevant data.

We can also use the & statement to bring two questions together.

In [10]:
df.loc[(df.revenue >= 50) & (df.units <= 4)]

    day  kind       key            name  units  revenue  best_price
0    11  Item        26   Deck Box Blue      3     61.5        20.5
12   11  Item         1  Basic Card Box      2     58.0        29.0
14   11  Card  0-39-4-F  EX Common Foil      1    645.0       645.0

The | (or) statement also works.

In [11]:
df.loc[(df.revenue >= 50) | (df.units <= 4)]

    day  kind        key                      name  units  revenue  best_price
0    11  Item         26             Deck Box Blue      3    61.50       20.50
1    11  Item         88             System Gate 2      1    45.50       45.50
2    11  Item         86               Mafia Works      1    44.50       44.50
3    11  Item          0           Basic Card Pack     22    74.80        3.40
4    11  Item          2            Rare Card Pack      2    10.00        5.00
5    11  Item         30             D20 Dice Blue      5    85.00       17.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
8    11  Item         31            D20 Dice Black      1    11.76       11.76
9    11  Item          3             Rare Card Box      1    40.00       40.00
10   11  Card     0-10-4                   EX Rare      1    17.08       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item          1            Basic Card Box      2    58.00       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card   0-39-4-F            EX Common Foil      1   645.00      645.00

In [13]:
df.loc[df.units.isin([1,2])]

    day  kind        key                      name  units  revenue  best_price
1    11  Item         88             System Gate 2      1    45.50       45.50
2    11  Item         86               Mafia Works      1    44.50       44.50
4    11  Item          2            Rare Card Pack      2    10.00        5.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
8    11  Item         31            D20 Dice Black      1    11.76       11.76
9    11  Item          3             Rare Card Box      1    40.00       40.00
10   11  Card     0-10-4                   EX Rare      1    17.08       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item          1            Basic Card Box      2    58.00       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card   0-39-4-F            EX Common Foil      1   645.00      645.00

We can use the isin function to tell pandas to only retrieve rows with those values.

In [16]:
df.loc[df.kind.notnull()]

    day  kind        key                      name  units  revenue  best_price
0    11  Item         26             Deck Box Blue      3    61.50       20.50
1    11  Item         88             System Gate 2      1    45.50       45.50
2    11  Item         86               Mafia Works      1    44.50       44.50
3    11  Item          0           Basic Card Pack     22    74.80        3.40
4    11  Item          2            Rare Card Pack      2    10.00        5.00
5    11  Item         30             D20 Dice Blue      5    85.00       17.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
8    11  Item         31            D20 Dice Black      1    11.76       11.76
9    11  Item          3             Rare Card Box      1    40.00       40.00
10   11  Card     0-10-4                   EX Rare      1    17.08       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item          1            Basic Card Box      2    58.00       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card   0-39-4-F            EX Common Foil      1   645.00      645.00

The notnull/isnull function shows functions that highlights values that are not empty or empty.

### Assigning Data

In [21]:
df['rating'] = 100
df['rating']

0     100
1     100
2     100
3     100
4     100
5     100
6     100
7     100
8     100
9     100
10    100
11    100
12    100
13    100
14    100
Name: rating, dtype: int64

We can assign data to a constant value, or a range of values.

In [24]:
df['index'] = range(0,len(df),1)
df['index']

0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
11    11
12    12
13    13
14    14
Name: index, dtype: int64