# Summary Functions & Maps (using TCG Card Shop sales data)

In [6]:
import pandas as pd

In [9]:
df = pd.read_csv('(testing) sales.csv')
df

    day  kind        key                      name  units  revenue  best_price
0    11  Item         26             Deck Box Blue      3    61.50       20.50
1    11  Item         88             System Gate 2      1    45.50       45.50
2    11  Item         86               Mafia Works      1    44.50       44.50
3    11  Item          0           Basic Card Pack     22    74.80        3.40
4    11  Item          2            Rare Card Pack      2    10.00        5.00
5    11  Item         30             D20 Dice Blue      5    85.00       17.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1    31.00       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1    33.00       33.00
8    11  Item         31            D20 Dice Black      1    11.76       11.76
9    11  Item          3             Rare Card Box      1    40.00       40.00
10   11  Card     0-10-4                   EX Rare      1    17.08       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1    29.33       29.33
12   11  Item          1            Basic Card Box      2    58.00       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1    25.32       25.32
14   11  Card   0-39-4-F            EX Common Foil      1   645.00      645.00

We can use summary functions to give us useful data about our, well, data.

In [10]:
df.revenue.describe()

count     15.000000
mean      80.786000
std      157.622401
min       10.000000
25%       27.325000
50%       40.000000
75%       59.750000
max      645.000000
Name: revenue, dtype: float64

The `describe()` function tells use some useful statistics about a certain column like the number of entries, mean, standard deviation, and much more.

In [11]:
df.name.describe()

count                           15
unique                          12
top       Silver Edition Rare Foil
freq                             4
Name: name, dtype: object

When we use it on a column with string data, it gives us different information about the column.

In [12]:
df.best_price.mean()

np.float64(66.49266666666666)

In [13]:
df.best_price.median()

np.float64(29.0)

We can also use functions like `mean()` and `median()`

In [15]:
df.best_price.mode()

0       3.40
1       5.00
2      11.76
3      17.00
4      17.08
5      20.50
6      25.32
7      29.00
8      29.33
9      31.00
10     33.00
11     40.00
12     44.50
13     45.50
14    645.00
Name: best_price, dtype: float64

In [16]:
df.units.mode()

0    1
Name: units, dtype: int64

The `mode()` function always returns a series as there can be multiple modes

We can use the `unique()` function to give us a list of the unique values in a column.

In [17]:
df.name.unique()

<StringArray>
[           'Deck Box Blue',            'System Gate 2',
              'Mafia Works',          'Basic Card Pack',
           'Rare Card Pack',            'D20 Dice Blue',
 'Silver Edition Rare Foil',           'D20 Dice Black',
            'Rare Card Box',                  'EX Rare',
           'Basic Card Box',           'EX Common Foil']
Length: 12, dtype: str

We can also see how many times a unique value appears in the column.

In [19]:
df.name.value_counts()

name
Silver Edition Rare Foil    4
Deck Box Blue               1
System Gate 2               1
Mafia Works                 1
Basic Card Pack             1
Rare Card Pack              1
D20 Dice Blue               1
D20 Dice Black              1
Rare Card Box               1
EX Rare                     1
Basic Card Box              1
EX Common Foil              1
Name: count, dtype: int64

### Maps

Maps are used to create new representations from existing data.

In [27]:
df_revenue_mean = df.revenue.mean()
dd = df.revenue.map(lambda p: p - df_revenue_mean)
dd

0     -19.286
1     -35.286
2     -36.286
3      -5.986
4     -70.786
5       4.214
6     -49.786
7     -47.786
8     -69.026
9     -40.786
10    -63.706
11    -51.456
12    -22.786
13    -55.466
14    564.214
Name: revenue, dtype: float64

We can use the map function to remean the column to zero.

We can also use the apply function to transform an entire dataframe.

In [31]:
def remean_revenue(row):
    row.revenue = row.revenue - df_revenue_mean
    return row

df.apply(remean_revenue, axis = 'columns')

    day  kind        key                      name  units  revenue  best_price
0    11  Item         26             Deck Box Blue      3  -19.286       20.50
1    11  Item         88             System Gate 2      1  -35.286       45.50
2    11  Item         86               Mafia Works      1  -36.286       44.50
3    11  Item          0           Basic Card Pack     22   -5.986        3.40
4    11  Item          2            Rare Card Pack      2  -70.786        5.00
5    11  Item         30             D20 Dice Blue      5    4.214       17.00
6    11  Card   0-14-2-F  Silver Edition Rare Foil      1  -49.786       31.00
7    11  Card  0-109-2-F  Silver Edition Rare Foil      1  -47.786       33.00
8    11  Item         31            D20 Dice Black      1  -69.026       11.76
9    11  Item          3             Rare Card Box      1  -40.786       40.00
10   11  Card     0-10-4                   EX Rare      1  -63.706       17.08
11   11  Card   0-18-2-F  Silver Edition Rare Foil      1  -51.456       29.33
12   11  Item          1            Basic Card Box      2  -22.786       29.00
13   11  Card   0-57-2-F  Silver Edition Rare Foil      1  -55.466       25.32
14   11  Card   0-39-4-F            EX Common Foil      1  564.214      645.00

This does the exact same thing as the map function. It also creates a new dataframe rather than modifying the original one.

In [32]:
df.head(1)

   day  kind key           name  units  revenue  best_price
0   11  Item  26  Deck Box Blue      3     61.5        20.5

As you can see the revenue column is unmodified.

Pandas also has many common mapping features as built ins.

In [33]:
df_revenue_mean = df.revenue.mean()
df.revenue - df_revenue_mean

0     -19.286
1     -35.286
2     -36.286
3      -5.986
4     -70.786
5       4.214
6     -49.786
7     -47.786
8     -69.026
9     -40.786
10    -63.706
11    -51.456
12    -22.786
13    -55.466
14    564.214
Name: revenue, dtype: float64

Pandas understands that we are trying to subtract every value in the series by the mean.

We can also use this to combine string data from two seperate column into one series.

In [36]:
df.kind + " - " + df.name

0                Item - Deck Box Blue
1                Item - System Gate 2
2                  Item - Mafia Works
3              Item - Basic Card Pack
4               Item - Rare Card Pack
5                Item - D20 Dice Blue
6     Card - Silver Edition Rare Foil
7     Card - Silver Edition Rare Foil
8               Item - D20 Dice Black
9                Item - Rare Card Box
10                     Card - EX Rare
11    Card - Silver Edition Rare Foil
12              Item - Basic Card Box
13    Card - Silver Edition Rare Foil
14              Card - EX Common Foil
dtype: str